package com.tpex.admin.repository;

import java.util.List;

import javax.persistence.Tuple;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.tpex.admin.entity.FinalDestEntity;

@Repository
public interface FinalDestRepository extends JpaRepository<FinalDestEntity, String> {

	List<FinalDestEntity> findAllByOrderByDestinationCdAsc();

	FinalDestEntity findAllByDestinationCd(String destCode);
	
	@Query(value = " SELECT   PLANT_CD , \r\n"
			+ " VAN_PLNT_NM , \r\n"
			+ " VAN_SEQ , \r\n"
			+ " case when SHIFT_CD = '' then null else SHIFT_CD  end SHIFT_CD , \r\n"
			+ " REQ_DT , \r\n"
			+ "                       CASE WHEN DELV_PLAN_TM = '' THEN null ELSE DELV_PLAN_TM END DELV_PLAN_TM , \r\n"
			+ "                       case when NPCS_VAN_FNL_ST_TM = '' then null else NPCS_VAN_FNL_ST_TM end NPCS_VAN_FNL_ST_TM,  \r\n"
			+ "                       CASE WHEN NPCS_VAN_FNL_END_TM = '' THEN null ELSE NPCS_VAN_FNL_END_TM END NPCS_VAN_FNL_END_TM, \r\n"
			+ "                       CASE WHEN ACT_VAN_STRT_TM = '' THEN null ELSE ACT_VAN_STRT_TM END ACT_VAN_STRT_TM , \r\n"
			+ "                       CASE WHEN ACT_VAN_END_TM = '' THEN null ELSE ACT_VAN_END_TM END ACT_VAN_END_TM  , \r\n"
			+ "                       QTY_20          , \r\n"
			+ "                       QTY_40          , \r\n"
			+ "                       ETD_DT          , \r\n"
			+ "                       SHP_COMP        , \r\n"
			+ "                       BOOK_NO         , \r\n"
			+ "                       VESS_NM         , \r\n"
			+ "                       CNT_ISO_NO ,       \r\n"
			+ "                       CASE WHEN SEAL_NO = '' THEN null ELSE SEAL_NO END SEAL_NO , \r\n"
			+ "                       DST_NM          ,   \r\n"
			+ "                       DST_CD          ,   \r\n"
			+ "                       RENBAN_CD       ,   \r\n"
			+ "                       CASE WHEN GPAC_CLOSE = '' THEN null ELSE GPAC_CLOSE END GPAC_CLOSE , \r\n"
			+ "                       SUM(MOD_QTY)    MOD_QTY,\r\n"
			+ "                       CASE WHEN NPCS_DOCK_NO = '' THEN null ELSE NPCS_DOCK_NO  END NPCS_DOCK_NO , \r\n"
			+ "                       CASE WHEN NPCS_CYC_TM = '' THEN null ELSE NPCS_CYC_TM END NPCS_CYC_TM , \r\n"
			+ "                       CASE WHEN REMARK = '' THEN null ELSE REMARK END REMARK , \r\n"
			+ "                       CONT_NET_WT,\r\n"
			+ "                       CB_CD, Tare_Weight \r\n"
			+ "              FROM(\r\n"
			+ "              SELECT DCR_VAN_DT.VAN_PLNT_CD                               PLANT_CD        ,\r\n"
			+ "                                 OPM.PLANT_NAME                           VAN_PLNT_NM     ,\r\n"
			+ "                                 ''                                       SHIFT_CD        ,\r\n"
			+ "                                 LPAD(DCR_VAN_DT.VAN_SEQ,3,'0')           VAN_SEQ         ,\r\n"
			+ "                                 (DCR_VAN_DT.VAN_DT - 0)  REQ_DT          ,\r\n"
			+ "                                 ''                                       DELV_PLAN_TM    ,\r\n"
			+ "                                 ''                                       NPCS_VAN_FNL_ST_TM,\r\n"
			+ "                                 ''                                       NPCS_VAN_FNL_END_TM,\r\n"
			+ "                                 ''                                       ACT_VAN_STRT_TM ,\r\n"
			+ "                                 ''                                       ACT_VAN_END_TM  ,\r\n"
			+ "                                 DCR_VAN_DT.QTY_20                        QTY_20          ,\r\n"
			+ "                                 DCR_VAN_DT.QTY_40                        QTY_40          ,\r\n"
			+ "                                 DCR_VAN_DT.ETD_1                         ETD_DT          ,\r\n"
			+ "                                 DCR_VAN_DT.SHP_NM_1                      SHP_COMP        ,\r\n"
			+ "                                 DCR_VAN_DT.BOOK_NO                       BOOK_NO         ,\r\n"
			+ "                                 DCR_VAN_DT.VESSEL1                       VESS_NM         ,\r\n"
			+ "                                 DCR_VAN_DT.ISO_CONT_NO                   CNT_ISO_NO      ,\r\n"
			+ "                                 ''                                       SEAL_NO         ,\r\n"
			+ "                                 FDM.DST_NM                            DST_NM          ,\r\n"
			+ "                                 DCR_VAN_DT.CONT_DST_CD                   DST_CD          ,\r\n"
			+ "                                 DCR_VAN_DT.CONT_RENBAN_NO                RENBAN_CD       ,\r\n"
			+ "                                 ''                                       GPAC_CLOSE      ,\r\n"
			+ "                                 DCR_VAN_DT.MOD_QTY                       MOD_QTY         ,\r\n"
			+ "                                 ''                                       NPCS_DOCK_NO    ,\r\n"
			+ "                                 ''                                       NPCS_CYC_TM     ,\r\n"
			+ "                           ''                                       REMARK,\r\n"
			+ "                           VAN_LN                             VAN_LN,\r\n"
			+ "                           CONT_DST_CD                   CONT_DST_CD,\r\n"
			+ "                           CONT_NET_WT,\r\n"
			+ "                           CB_CD, Tare_Weight \r\n"
			+ "                  FROM (SELECT NVDC.PLN_VAN_END_DT                         VAN_DT        ,\r\n"
			+ "                           NVDC.PLN_VAN_END_TM                             VAN_TM_HR     ,\r\n"
			+ "                           CASE NVDC.CONT_SIZE WHEN 20 THEN 1 ELSE 0 END   QTY_20        ,\r\n"
			+ "                                       CASE NVDC.CONT_SIZE WHEN 40 THEN 1 ELSE 0 END   QTY_40        ,\r\n"
			+ "                                           NVDC.CONT_GRP_CD                            RENBAN_CD     ,\r\n"
			+ "                                           NVDC.ETD_1                              ETD_1         ,\r\n"
			+ "                                           NVDC.SHP_NM_1                           SHP_NM_1      ,\r\n"
			+ "                                           NVDC.VAN_PLNT_CD                             VAN_PLNT_CD   ,\r\n"
			+ "                                           NRBM.BOOK_NO                            BOOK_NO       ,\r\n"
			+ "                                           NRBM.VESSEL1                                 VESSEL1       ,\r\n"
			+ "                                           NICM.ISO_CONT_NO                        ISO_CONT_NO   ,\r\n"
			+ "                                           NVDC.CONT_DST_CD                        CONT_DST_CD   ,\r\n"
			+ "                                           NVDC.CONT_SNO                           CONT_RENBAN_NO,\r\n"
			+ "                                           NVDM.TOT_MOD                                                 MOD_QTY           ,\r\n"
			+ "                                           NVDC.VAN_LN                                             VAN_LN            ,\r\n"
			+ "                                           NVDC.VAN_SEQ_NO                                 VAN_SEQ,\r\n"
			+ "                                           NVDC.CONT_NET_WT                                 CONT_NET_WT,\r\n"
			+ "                                           NRBM.CB_CD                                            CB_CD, \r\n"
			+ "                                           NICM.Tare_Weight                                            Tare_Weight \r\n"
			+ "                                FROM   TB_R_DLY_VPR_CONTAINER      NVDC    LEFT OUTER JOIN tb_m_iso_container NICM \r\n"
			+ "                                ON   NVDC.PKG_MTH      = NICM.CONT_VAN_MTH\r\n"
			+ "                                AND   NVDC.CONT_DST_CD  = NICM.CONT_DST_CD\r\n"
			+ "                                AND   NVDC.CONT_SNO     = NICM.CONT_SNO,\r\n"
			+ "                                           (SELECT VDC.PKG_MTH      ,\r\n"
			+ "                                                           VDC.CONT_DST_CD  ,\r\n"
			+ "                                                           VDC.CONT_SNO     ,\r\n"
			+ "                                                           COUNT(DISTINCT VDM.CTRL_MOD_NO)  TOT_MOD \r\n"
			+ "                                                FROM   TB_R_DLY_VPR_MODULE  VDM, TB_R_DLY_VPR_CONTAINER VDC \r\n"
			+ "                                                WHERE      VDM.CONT_DST_CD  = VDC.CONT_DST_CD \r\n"
			+ "                                                AND        VDM.CONT_SNO     = VDC.CONT_SNO \r\n"
			+ "                                                AND        VDC.PKG_MTH      = :vanMonth \r\n"		
			+ "                                                GROUP  BY VDC.PKG_MTH,VDC.CONT_DST_CD,VDC.CONT_SNO\r\n"
			+ "                                                )                                         NVDM ,\r\n"
			+ "                                               TB_R_MTH_RENBAN_BOOKING_H  NRBM ,\r\n"
			+ " TB_R_MTH_RENBAN_BOOKING_D  NRBD   \r\n"
			+ "                                WHERE NVDC.PKG_MTH      = NVDM.PKG_MTH\r\n"
			+ "                                AND   NVDC.CONT_DST_CD  = NVDM.CONT_DST_CD\r\n"
			+ "                                AND   NVDC.CONT_SNO     = NVDM.CONT_SNO\r\n"
			+ "                                AND   NVDC.PKG_MTH      = NRBD.CONT_VAN_MTH\r\n"
			+ "                                AND   NVDC.CONT_DST_CD  = NRBD.CONT_DST_CD\r\n"
			+ "                                AND   NVDC.ETD_1        = NRBD.ETD1\r\n"
			+ "                                AND   NVDC.SHP_NM_1     = NRBD.SHP_NM_1\r\n"
			+ "                                AND   NVDC.CONT_GRP_CD  = NRBD.CONT_GRP_CD\r\n"
			+ "                                AND   NRBD.CONT_VAN_MTH = NRBM.CONT_VAN_MTH\r\n"
			+ "                                AND   NRBD.CONT_DST_CD  = NRBM.CONT_DST_CD\r\n"
			+ "                                AND   NRBD.ETD1         = NRBM.ETD1\r\n"
			+ "                                AND   NRBD.SHP_NM_1     = NRBM.SHP_NM_1\r\n"
			+ "                                AND   NRBD.GROUP_ID     = NRBM.GROUP_ID\r\n"		
			+ "                                AND ( :vanPlant IS NULL OR NVDC.VAN_PLNT_CD = :vanPlant ) \r\n"
			+ "                                AND NVDC.PLN_VAN_END_DT = :etdDate \r\n"
			+ "                                AND   NRBD.CONT_VAN_MTH = :vanMonth \r\n"
			+ "                                AND   NRBM.CONT_VAN_MTH = :vanMonth \r\n"
			+ "                                AND   NVDC.PKG_MTH      = :vanMonth \r\n"
			+ "                                )                DCR_VAN_DT ,\r\n"
			+ "                                TB_M_FINAL_DESTINATION  FDM        ,\r\n"
			+ "                                TB_M_PLANT     OPM\r\n"
			+ "                  WHERE DCR_VAN_DT.CONT_DST_CD = FDM.DST_CD\r\n"
			+ "                  AND   DCR_VAN_DT.VAN_PLNT_CD = OPM.PLANT_CD\r\n"
			+ "                         -- FLP         \r\n"
			+ "                         \r\n"
			+ "                         UNION ALL\r\n"
			+ "                          SELECT \r\n"
			+ "                           DCR_VAN_DT.VAN_PLNT_CD                               PLANT_CD        ,\r\n"
			+ "                           OPM.PLANT_NAME                          VAN_PLNT_NM     ,\r\n"
			+ "                           ''                                       SHIFT_CD        ,\r\n"
			+ "                           LPAD(DCR_VAN_DT.VAN_SEQ,3,'0')           VAN_SEQ         ,\r\n"
			+ "                           (DCR_VAN_DT.VAN_DT - 0)  REQ_DT          ,\r\n"
			+ "                           ''                                       DELV_PLAN_TM    ,\r\n"
			+ "                           ''                                       NPCS_VAN_FNL_ST_TM,\r\n"
			+ "                           ''                                       NPCS_VAN_FNL_END_TM,\r\n"
			+ "                           ''                                       ACT_VAN_STRT_TM ,\r\n"
			+ "                           ''                                       ACT_VAN_END_TM  ,\r\n"
			+ "                           DCR_VAN_DT.QTY_20                        QTY_20          ,\r\n"
			+ "                           DCR_VAN_DT.QTY_40                        QTY_40          ,\r\n"
			+ "                           DCR_VAN_DT.ETD_1                         ETD_DT          ,\r\n"
			+ "                           DCR_VAN_DT.SHP_NM_1                      SHP_COMP        ,\r\n"
			+ "                           DCR_VAN_DT.BOOK_NO                       BOOK_NO         ,\r\n"
			+ "                           DCR_VAN_DT.VESSEL1                       VESS_NM         ,\r\n"
			+ "                           DCR_VAN_DT.ISO_CONT_NO                   CNT_ISO_NO      ,\r\n"
			+ "                           ''                                       SEAL_NO         ,\r\n"
			+ "                           FDM.DST_NM                            DST_NM          ,\r\n"
			+ "                           DCR_VAN_DT.CONT_DST_CD                   DST_CD          ,\r\n"
			+ "                           DCR_VAN_DT.CONT_RENBAN_NO                RENBAN_CD       ,\r\n"
			+ "                           ''                                       GPAC_CLOSE      ,\r\n"
			+ "                           DCR_VAN_DT.MOD_QTY                       MOD_QTY         ,\r\n"
			+ "                           ''                                       NPCS_DOCK_NO    ,\r\n"
			+ "                           ''                                       NPCS_CYC_TM     ,\r\n"
			+ "                           ''                                       REMARK,\r\n"
			+ "                           VAN_LN                             VAN_LN,\r\n"
			+ "                           CONT_DST_CD                   CONT_DST_CD,\r\n"
			+ "                           CONT_NET_WT,\r\n"
			+ "                           CB_CD, Tare_Weight \r\n"
			+ "                        FROM (SELECT \r\n"
			+ "                                 NVDC.PLN_VAN_END_DT                         VAN_DT        ,\r\n"
			+ "                                 NVDC.PLN_VAN_END_TM                         VAN_TM_HR     ,\r\n"
			+ "                                 CASE NVDC.CONT_SIZE WHEN 20 THEN 1 ELSE 0 END               QTY_20        ,\r\n"
			+ "                                 CASE NVDC.CONT_SIZE WHEN 40 THEN 1 ELSE 0 END   QTY_40        ,\r\n"
			+ "                                 NVDC.CONT_GRP_CD                            RENBAN_CD     ,\r\n"
			+ "                                 NVDC.ETD_1                              ETD_1         ,\r\n"
			+ "                                 NVDC.SHP_NM_1                           SHP_NM_1      ,\r\n"
			+ "                                 NVDC.VAN_PLNT_CD                             VAN_PLNT_CD   ,\r\n"
			+ "                                 NRBM.BOOK_NO                            BOOK_NO       ,\r\n"
			+ "                                 NRBM.VESSEL1                                 VESSEL1       ,\r\n"
			+ "                                 NICM.ISO_CONT_NO                        ISO_CONT_NO   ,\r\n"
			+ "                                 NVDC.CONT_DST_CD                        CONT_DST_CD   ,\r\n"
			+ "                                 NVDC.CONT_SNO                           CONT_RENBAN_NO,\r\n"
			+ "                                 NVDM.TOT_MOD                                                 MOD_QTY           ,\r\n"
			+ "                                 NVDC.VAN_LN                                             VAN_LN            ,\r\n"
			+ "                                 NVDC.VAN_SEQ_NO                                 VAN_SEQ,\r\n"
			+ "                                 NVDC.CONT_NET_WT                                   CONT_NET_WT,\r\n"
			+ "                                 NRBM.CB_CD                           CB_CD , \r\n"
			+ "                                 NICM.Tare_Weight                           Tare_Weight \r\n"
			+ "                              FROM   \r\n"
			+ "                                 TB_R_DLY_VPR_CONTAINER      NVDC  LEFT OUTER JOIN tb_m_iso_container     NICM\r\n"
			+ "                                ON   NVDC.PKG_MTH      = NICM.CONT_VAN_MTH\r\n"
			+ "                                AND   NVDC.CONT_DST_CD  = NICM.CONT_DST_CD\r\n"
			+ "                                AND   NVDC.CONT_SNO     = NICM.CONT_SNO,\r\n"
			+ "                                 (SELECT VDC.PKG_MTH      ,\r\n"
			+ "                                         VDC.CONT_DST_CD  ,\r\n"
			+ "                                         VDC.CONT_SNO     ,\r\n"
			+ "                                         COUNT(DISTINCT VDM.CTRL_MOD_NO)  TOT_MOD\r\n"
			+ "                                  FROM   TB_R_VPP_DLY_MOD  VDM, TB_R_DLY_VPR_CONTAINER VDC\r\n"
			+ "                                  WHERE  VDM.CONT_DST_CD  = VDC.CONT_DST_CD\r\n"
			+ "                                  AND        VDM.CONT_SNO = VDC.CONT_SNO\r\n"
			+ "                                  AND        VDC.PKG_MTH  = :vanMonth \r\n"		
			+ "                                  AND NOT EXISTS ( SELECT 1 FROM TB_R_DLY_VPR_MODULE T1 WHERE VDM.CTRL_MOD_NO = T1.CTRL_MOD_NO)\r\n"
			+ "                                  AND  IFNULL(VDM.MOD_STS,'N')      <> 'C'\r\n"
			+ "                                  GROUP  BY VDC.PKG_MTH,VDC.CONT_DST_CD,VDC.CONT_SNO\r\n"
			+ "                                 )                                         NVDM ,\r\n"
			+ "                                 TB_R_MTH_RENBAN_BOOKING_H  NRBM ,\r\n"
			+ "                              TB_R_MTH_RENBAN_BOOKING_D  NRBD \r\n"
			+ "                              WHERE NVDC.PKG_MTH      = NVDM.PKG_MTH \r\n"
			+ "                              AND   NVDC.CONT_DST_CD  = NVDM.CONT_DST_CD \r\n"
			+ "                              AND   NVDC.CONT_SNO     = NVDM.CONT_SNO \r\n"
			+ "                              AND   NVDC.PKG_MTH      = NRBD.CONT_VAN_MTH \r\n"
			+ "                              AND   NVDC.CONT_DST_CD  = NRBD.CONT_DST_CD \r\n"
			+ "                              AND   NVDC.ETD_1        = NRBD.ETD1 \r\n"
			+ "                              AND   NVDC.SHP_NM_1     = NRBD.SHP_NM_1 \r\n"
			+ "                              AND   NVDC.CONT_GRP_CD  = NRBD.CONT_GRP_CD \r\n"
			+ "                              AND   NRBD.CONT_VAN_MTH = NRBM.CONT_VAN_MTH \r\n"
			+ "                              AND   NRBD.CONT_DST_CD  = NRBM.CONT_DST_CD \r\n"
			+ "                              AND   NRBD.ETD1         = NRBM.ETD1 \r\n"
			+ "                              AND   NRBD.SHP_NM_1     = NRBM.SHP_NM_1 \r\n"
			+ "                              AND   NRBD.GROUP_ID     = NRBM.GROUP_ID \r\n"			
			+ "                              AND   ( :vanPlant IS NULL OR NVDC.VAN_PLNT_CD = :vanPlant)\r\n"
			+ "                              AND       NVDC.PLN_VAN_END_DT = :etdDate \r\n"
			+ "                              AND   NRBD.CONT_VAN_MTH = :vanMonth \r\n"
			+ "                              AND   NRBM.CONT_VAN_MTH = :vanMonth \r\n"
			+ "                              AND   NVDC.PKG_MTH      = :vanMonth \r\n"
			+ "                                   ) DCR_VAN_DT ,\r\n"
			+ "                                    TB_M_FINAL_DESTINATION  FDM        ,\r\n"
			+ "                                TB_M_PLANT     OPM\r\n"
			+ "                  WHERE DCR_VAN_DT.CONT_DST_CD = FDM.DST_CD\r\n"
			+ "                  AND   DCR_VAN_DT.VAN_PLNT_CD = OPM.PLANT_CD) MAIN\r\n"
			+ "                        GROUP BY\r\n"
			+ "                                PLANT_CD        ,   \r\n"
			+ "                                VAN_PLNT_NM     ,   \r\n"
			+ "                                SHIFT_CD        ,   \r\n"
			+ "                                VAN_SEQ         ,   \r\n"
			+ "                                REQ_DT          ,   \r\n"
			+ "                                DELV_PLAN_TM    ,   \r\n"
			+ "                                NPCS_VAN_FNL_ST_TM, \r\n"
			+ "                                NPCS_VAN_FNL_END_TM,\r\n"
			+ "                                ACT_VAN_STRT_TM ,   \r\n"
			+ "                                ACT_VAN_END_TM  ,   \r\n"
			+ "                                QTY_20          ,   \r\n"
			+ "                                QTY_40          ,   \r\n"
			+ "                                ETD_DT          ,   \r\n"
			+ "                                SHP_COMP        ,   \r\n"
			+ "                                BOOK_NO         ,   \r\n"
			+ "                                VESS_NM         ,   \r\n"
			+ "                                CNT_ISO_NO      ,   \r\n"
			+ "                                SEAL_NO         ,   \r\n"
			+ "                                DST_NM          ,   \r\n"
			+ "                                DST_CD          ,   \r\n"
			+ "                                RENBAN_CD       ,   \r\n"
			+ "                                GPAC_CLOSE      ,   \r\n"
			+ "                                NPCS_DOCK_NO    ,   \r\n"
			+ "                                NPCS_CYC_TM     ,   \r\n"
			+ "                                REMARK           ,\r\n"
			+ "                                VAN_LN,\r\n"
			+ "                                CONT_DST_CD,\r\n"
			+ "                                CONT_NET_WT,\r\n"
			+ "                                CB_CD, Tare_Weight \r\n"
			+ "                        ORDER BY PLANT_CD, VAN_LN,\r\n"
			+ "                                       VAN_SEQ,CONT_DST_CD,RENBAN_CD; \r\n ", nativeQuery = true)			
	List<Object[]> getContainerRequisitionData(@Param("vanMonth") String vanMonth, @Param("etdDate") String etdDate, @Param("vanPlant") String vanPlant);

	List<FinalDestEntity> findByCmpCd(String cmpCd);

}
