package com.tpex.admin.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.tpex.admin.entity.LotPartShortageEntity;
import com.tpex.admin.entity.LotPartShortageIdEntity;

@Repository
public interface LotPartShortageRepository extends JpaRepository<LotPartShortageEntity, LotPartShortageIdEntity> {

	@Query(value = "SELECT \r\n" + " case when INV_NO is null then 0 else case when sno=1 then 1 else 0 end end ITEM_NO,\r\n"
			+ "              INV_NO,\r\n" + "              REV_NO,\r\n"
			+ "              date_format(ETD,'%d/%m/%Y') ETD,\r\n" + "              DEST_CD,\r\n"
			+ "              ORD_NO,\r\n" + "              CF_CD,\r\n" + "              CONT_SNO,\r\n"
			+ "              LOT_NO,\r\n" + "              CASE_CD,\r\n" + "              PART_NO,\r\n"
			+ "              PART_NAME,\r\n" + "              PLAN_QTY,\r\n" + "              ACT_QTY,\r\n"
			+ "              DIFF_QTY,\r\n" + "              SNO\r\n" + "         FROM (SELECT INV_NO,\r\n"
			+ "              REV_NO,\r\n" + "              ETD,\r\n" + "              DEST_CD,\r\n"
			+ "              ORD_NO,\r\n" + "              CF_CD,\r\n" + "              CONT_SNO,\r\n"
			+ "              LOT_NO,\r\n" + "              CASE_CD,\r\n" + "              PART_NO,\r\n"
			+ "              PART_NAME,\r\n" + "              PLAN_QTY,\r\n" + "              ACT_QTY,\r\n"
			+ "              DIFF_QTY,\r\n"
			+ "              RANK() OVER(PARTITION BY ETD,DEST_CD,ORD_NO,CF_CD,LOT_NO,CASE_CD,PART_NO ORDER BY REV_NO DESC) SNO\r\n"
			+ "         FROM (SELECT INV_NO,\r\n" + "                      REV_NO,\r\n"
			+ "                      ETD,\r\n" + "                      DEST_CD,\r\n"
			+ "                      ORD_NO,\r\n" + "                      CF_CD,\r\n"
			+ "                      CONT_SNO,\r\n" + "                      LOT_NO,\r\n"
			+ "                      CASE_CD,\r\n" + "                      PART_NO,\r\n"
			+ "                      PART_NAME,\r\n" + "                      PLAN_QTY,\r\n"
			+ "                      ACT_QTY,\r\n"
			+ "                      ifnull(PLAN_QTY,0) - ifnull(ACT_QTY,0) DIFF_QTY\r\n"
			+ "                 FROM (SELECT DISTINCT DTLS.INV_NO INV_NO,\r\n"
			+ "                              DTLS.REV_NO REV_NO,\r\n"
			+ "                              DTLS.ETD ETD,\r\n"
			+ "                              DTLS.DST_CD DEST_CD,\r\n"
			+ "                              DTLS.ORD_NO ORD_NO,\r\n"
			+ "                              DTLS.CF_CD CF_CD,\r\n"
			+ "                              DTLS.CONT_SNO CONT_SNO,\r\n"
			+ "                              DTLS.LOT_MOD_NO LOT_NO,\r\n"
			+ "                              DTLS.CASE_NO CASE_CD ,\r\n"
			+ "                              DTLS.PART_NO PART_NO,\r\n"
			+ "                              DTLS.PART_NM PART_NAME,\r\n"
			+ "                              SUM(DTLS.PLN_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) PLAN_QTY,\r\n"
			+ "                              SUM(DTLS.ACT_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) ACT_QTY\r\n"
			+ "                         FROM TB_R_LOT_PART_SHORT_D DTLS \r\n"
			+ "                         WHERE DATE_FORMAT (ETD,'%m/%Y') = :etdMonth\r\n"
			+ "                          AND (:destination     IS NULL OR DTLS.DST_CD  = :destination)\r\n"
			+ "                         AND (:carFamilyCode       IS NULL OR DTLS.CF_CD   = :carFamilyCode)\r\n"
			+ "                         AND (:pkgMonth IS NULL OR DTLS.PKG_MTH = :pkgMonth)\r\n"
			+ "                          AND (:invoiceNo   IS NULL OR DTLS.INV_NO  = :invoiceNo)\r\n"
			+ "                          AND (STR_TO_DATE(:etdDate,'%d/%m/%Y')   IS NULL OR DTLS.ETD     = STR_TO_DATE(:etdDate,'%d/%m/%Y'))\r\n"
			+ "                    ) as T\r\n" + "            ) AS T1\r\n"
			+ "            ) AS T2 ORDER BY ifnull(INV_NO,' '), ETD,DEST_CD,ORD_NO,INV_NO,CF_CD,CONT_SNO,LOT_NO,CASE_CD,PART_NO,REV_NO;", nativeQuery = true)
	List<Object[]> getAllData(@Param("etdMonth") String etdMonth, @Param("destination") String destination,
			@Param("carFamilyCode") String carFamilyCode, @Param("pkgMonth") String pkgMonth, @Param("invoiceNo") String invoiceNo,
			@Param("etdDate") String etdDate);

	@Query(value = "SELECT case when INV_NO is null then 0 else case when sno=1 then 1 else 0 end end ITEM_NO,\r\n"
			+ "            INV_NO,\r\n"
			+ "            REV_NO,\r\n"
			+ "            date_format(ETD,'%d/%m/%Y') ETD,\r\n"
			+ "            DEST_CD,\r\n"
			+ "            ORD_NO,\r\n"
			+ "            CF_CD,\r\n"
			+ "            CONT_SNO,\r\n"
			+ "            LOT_NO,\r\n"
			+ "            CASE_CD,\r\n"
			+ "            PART_NO,\r\n"
			+ "            PART_NAME,\r\n"
			+ "            PLAN_QTY,\r\n"
			+ "            ACT_QTY,\r\n"
			+ "            DIFF_QTY,\r\n"
			+ "            SNO\r\n"
			+ "      FROM (SELECT INV_NO,\r\n"
			+ "                   REV_NO,\r\n"
			+ "                   ETD,\r\n"
			+ "                   DEST_CD,\r\n"
			+ "                   ORD_NO,\r\n"
			+ "                   CF_CD,\r\n"
			+ "                   CONT_SNO,\r\n"
			+ "                   LOT_NO,\r\n"
			+ "                   CASE_CD,\r\n"
			+ "                   PART_NO,\r\n"
			+ "                   PART_NAME,\r\n"
			+ "                   PLAN_QTY,\r\n"
			+ "                   ACT_QTY,\r\n"
			+ "                   DIFF_QTY,\r\n"
			+ "                   RANK() OVER(PARTITION BY ETD,DEST_CD,ORD_NO,CF_CD,LOT_NO,CASE_CD,PART_NO ORDER BY REV_NO DESC) SNO\r\n"
			+ "              FROM (SELECT INV_NO,\r\n"
			+ "                           REV_NO,\r\n"
			+ "                           ETD,\r\n"
			+ "                           DEST_CD,\r\n"
			+ "                           ORD_NO,\r\n"
			+ "                           CF_CD,\r\n"
			+ "                           CONT_SNO,\r\n"
			+ "                           LOT_NO,\r\n"
			+ "                           CASE_CD,\r\n"
			+ "                           PART_NO,\r\n"
			+ "                           PART_NAME,\r\n"
			+ "                           PLAN_QTY,\r\n"
			+ "                           ACT_QTY,\r\n"
			+ "                           IFNULL(PLAN_QTY,0) - IFNULL(ACT_QTY,0) DIFF_QTY\r\n"
			+ "                      FROM (SELECT DISTINCT DTLS.INV_NO INV_NO,\r\n"
			+ "                                   DTLS.REV_NO REV_NO,\r\n"
			+ "                                   DTLS.ETD ETD,\r\n"
			+ "                                   DTLS.DST_CD DEST_CD,\r\n"
			+ "                                   DTLS.ORD_NO ORD_NO,\r\n"
			+ "                                   DTLS.CF_CD CF_CD,\r\n"
			+ "                                   DTLS.CONT_SNO CONT_SNO,\r\n"
			+ "                                   DTLS.LOT_MOD_NO LOT_NO,\r\n"
			+ "                                   DTLS.CASE_NO CASE_CD ,\r\n"
			+ "                                   DTLS.PART_NO PART_NO,\r\n"
			+ "                                   DTLS.PART_NM PART_NAME,\r\n"
			+ "                                   SUM(DTLS.PLN_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) PLAN_QTY,\r\n"
			+ "                                   SUM(DTLS.ACT_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) ACT_QTY\r\n"
			+ "                              FROM TB_R_LOT_PART_SHORT_D DTLS\r\n"
			+ "                             WHERE DATE_FORMAT(ETD,'%m/%Y') = :etdMonth\r\n"
			+ "                               AND (:destination     IS NULL OR DTLS.DST_CD  = :destination)\r\n"
			+ "                               AND (:carFamilyCode       IS NULL OR DTLS.CF_CD   = :carFamilyCode)\r\n"
			+ "                               AND (:pkgMonth IS NULL OR DTLS.PKG_MTH = :pkgMonth)\r\n"
			+ "                               AND (:invoiceNo   IS NULL OR DTLS.INV_NO  = :invoiceNo)\r\n"
			+ "                               AND (STR_TO_DATE(:etdDate,'%d/%m/%Y')      IS NULL OR DTLS.ETD     = STR_TO_DATE(:etdDate,'%d/%m/%Y'))\r\n"
			+ "                           ) as t\r\n"
			+ "                   ) as p\r\n"
			+ "           ) as t2 WHERE SNO = 1\r\n"
			+ "           ORDER BY IFNULL(INV_NO,' '),ETD,DEST_CD,ORD_NO,INV_NO,CF_CD,CONT_SNO,LOT_NO,CASE_CD,PART_NO,REV_NO;", nativeQuery = true)
	List<Object[]> getLatestData(@Param("etdMonth") String etdMonth, @Param("destination") String destination,
			@Param("carFamilyCode") String carFamilyCode, @Param("pkgMonth") String pkgMonth, @Param("invoiceNo") String invoiceNo,
			@Param("etdDate") String etdDate);

	@Query(value = "SELECT case when INV_NO is null then 0 else case when sno=1 then 1 else 0 end end ITEM_NO,\r\n"
			+ "            INV_NO,\r\n"
			+ "            REV_NO,\r\n"
			+ "            date_format(ETD,'%d/%m/%Y') ETD,\r\n"
			+ "            DEST_CD,\r\n"
			+ "            ORD_NO,\r\n"
			+ "            CF_CD,\r\n"
			+ "            CONT_SNO,\r\n"
			+ "            LOT_NO,\r\n"
			+ "            CASE_CD,\r\n"
			+ "            PART_NO,\r\n"
			+ "            PART_NAME,\r\n"
			+ "            PLAN_QTY,\r\n"
			+ "            ACT_QTY,\r\n"
			+ "            DIFF_QTY,\r\n"
			+ "            SNO\r\n"
			+ "       FROM (SELECT INV_NO,\r\n"
			+ "                    REV_NO,\r\n"
			+ "                    ETD,\r\n"
			+ "                    DEST_CD,\r\n"
			+ "                    ORD_NO,\r\n"
			+ "                    CF_CD,\r\n"
			+ "                    CONT_SNO,\r\n"
			+ "                    LOT_NO,\r\n"
			+ "                    CASE_CD,\r\n"
			+ "                    PART_NO,\r\n"
			+ "                    PART_NAME,\r\n"
			+ "                    PLAN_QTY,\r\n"
			+ "                    ACT_QTY,\r\n"
			+ "                    DIFF_QTY,\r\n"
			+ "                    RANK() OVER(PARTITION BY ETD,DEST_CD,ORD_NO,CF_CD,LOT_NO,CASE_CD,PART_NO ORDER BY REV_NO DESC) SNO\r\n"
			+ "               FROM (SELECT INV_NO,\r\n"
			+ "                            REV_NO,\r\n"
			+ "                            ETD,\r\n"
			+ "                            DEST_CD,\r\n"
			+ "                            ORD_NO,\r\n"
			+ "                            CF_CD,\r\n"
			+ "                            CONT_SNO,\r\n"
			+ "                            LOT_NO,\r\n"
			+ "                            CASE_CD,\r\n"
			+ "                            PART_NO,\r\n"
			+ "                            PART_NAME,\r\n"
			+ "                            PLAN_QTY,\r\n"
			+ "                            ACT_QTY,\r\n"
			+ "                            IFNULL(PLAN_QTY,0) - IFNULL(ACT_QTY,0) DIFF_QTY\r\n"
			+ "                       FROM (SELECT DISTINCT DTLS.INV_NO INV_NO,\r\n"
			+ "                                    DTLS.REV_NO REV_NO,\r\n"
			+ "                                    DTLS.ETD ETD,\r\n"
			+ "                                    DTLS.DST_CD DEST_CD,\r\n"
			+ "                                    DTLS.ORD_NO ORD_NO,\r\n"
			+ "                                    DTLS.CF_CD CF_CD,\r\n"
			+ "                                    DTLS.CONT_SNO CONT_SNO,\r\n"
			+ "                                    DTLS.LOT_MOD_NO LOT_NO,\r\n"
			+ "                                    DTLS.CASE_NO CASE_CD ,\r\n"
			+ "                                    DTLS.PART_NO PART_NO,\r\n"
			+ "                                    DTLS.PART_NM PART_NAME,\r\n"
			+ "                                    SUM(DTLS.PLN_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) PLAN_QTY,\r\n"
			+ "                                    SUM(DTLS.ACT_QTY) OVER(PARTITION BY INV_NO,REV_NO,ETD,DST_CD,ORD_NO,CF_CD,CONT_SNO,LOT_MOD_NO,CASE_NO,PART_NO) ACT_QTY\r\n"
			+ "                               FROM TB_R_LOT_PART_SHORT_D DTLS\r\n"
			+ "                              WHERE DATE_FORMAT(ETD,'%m/%Y') = :etdMonth\r\n"
			+ "                                AND (:destination     IS NULL OR DTLS.DST_CD  = :destination)\r\n"
			+ "                                AND (:carFamilyCode       IS NULL OR DTLS.CF_CD   = :carFamilyCode)\r\n"
			+ "                                AND (:pkgMonth IS NULL OR DTLS.PKG_MTH = :pkgMonth)\r\n"
			+ "                                AND (:invoiceNo   IS NULL OR DTLS.INV_NO  = :invoiceNo)\r\n"
			+ "                                AND (STR_TO_DATE(:etdDate,'%d/%m/%Y')      IS NULL OR DTLS.ETD     = STR_TO_DATE(:etdDate,'%d/%m/%Y'))\r\n"
			+ "                         ) AS T1\r\n"
			+ "                   ) AS T2\r\n"
			+ "            ) AS T3 WHERE REV_NO  = :revisionNo\r\n"
			+ "            ORDER BY IFNULL(INV_NO,' '),ETD,DEST_CD,ORD_NO,INV_NO,CF_CD,CONT_SNO,LOT_NO,CASE_CD,PART_NO,REV_NO", nativeQuery = true)
	List<Object[]> getData(@Param("etdMonth") String etdMonth, @Param("destination") String destination,
			@Param("carFamilyCode") String carFamilyCode, @Param("pkgMonth") String pkgMonth, @Param("invoiceNo") String invoiceNo,
			@Param("etdDate") String etdDate,@Param("revisionNo") String revisionNo);

}
