stages:
  - compile
  # - unit test
  - code scan  
  - image build
  - image scan
  - image push
  - dev deployment
  - sit deployment
  - uat approval
  - uat promote
  - uat deployment
  - prod approval
  - prod deployment
  - testing

# This folder is cached between builds
cache:
  paths:
    - node_modules/

variables:
  ### PROJECT_NAME and SERVICE_NAME cannot use underscore "_" test pipeline by norapatra
  PROJECT_NAME: "toyota-part-export-system" # Harbor repository name
  SERVICE_NAME: "tpex-ui-pwa-react" ## OpenShift service name
  SERVICE_VERSION: "v1.0.0" # Service version using for tagging on Harbor
  SOURCE_SCAN_PATH: "."
  #SONAR_CONFIG : "-Dsonar.java.binaries=. -Dsonar.qualitygate.timeout=360"


include:
  - project: "DevSecOps/cicd-template"
    ref: master
    file: "/templates/DS9/template-pipeline-v1.0.0.yml" 

compile:
  stage: compile
  image: $DOMAIN_NAME_TCR/hubdocker/library/node:14.17.4-slim
  tags:
    - docker
  script: 
    - echo "Start building App"
    - cd src
    - npm cache clean --force
    - npm install
    - echo "building successfully"
  only:
    - develop
    - release
    - /^hotfix-v[0-9]\d*(\.[0-9]\d*)*$/

# unit test:
#   stage: unit test
#   image: $DOMAIN_NAME_TCR/hubdocker/library/node:14.17.4-slim
#   tags:
#     - docker
#   script: 
#     - echo "Start unit test "
#     - 'jest --ci --reporters=default --reporters=jest-junit'
#     - echo "unit test successfully"
#   artifacts:
#     when: always
#     expire_in: 1 week
#     reports:
#       junit:
#         - junit.xml
#   only:
#     - develop
#     - release
#     - /^hotfix-v[0-9]\d*(\.[0-9]\d*)*$/
